language: bash

os:
- linux

env:
  - ELIXIRVER=
  - ELIXIRVER=1.7
  - ELIXIRVER=1.6
  - ELIXIRVER=1.5

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$BASHVER" ]]; then
    printf "FROM elixir:${ELIXIRVER}-alpine\nWORKDIR /code\nRUN apk add --update make\nENTRYPOINT []\nCMD [\"make\"]" > Dockerfile
    docker build --tag tester:${ELIXIRVER}-alpine .
    docker run -it -v `pwd`:/code tester:${ELIXIRVER}-alpine
  fi

notifications:
  email:
    on_success: never